### ISSUE TITLE
Undefined symbol: SSLv3_method

### ISSUE THREAD

**Issue by maxpshaw** [abhishek-ram/pyas2#30]
I keep getting this error message when I run "python manage.py makemigrations pyas2"; how do I fix this?

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/django/apps/config.py", line 197, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/pyas2/models.py", line 6, in <module>
    from pyas2 import pyas2init
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/pyas2/pyas2init.py", line 5, in <module>
    from pyas2 import as2utils
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/pyas2/as2utils.py", line 12, in <module>
    from M2Crypto import BIO, SMIME, X509
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, util
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/M2Crypto/BIO.py", line 10, in <module>
    from M2Crypto import m2, util
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/M2Crypto/m2.py", line 30, in <module>
    from M2Crypto._m2crypto import *
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/M2Crypto/_m2crypto.py", line 26, in <module>
    __m2crypto = swig_import_helper()
  File "/home/max/Projects/as2test/env/lib/python2.7/site-packages/M2Crypto/_m2crypto.py", line 22, in swig_import_helper
    _mod = imp.load_module('__m2crypto', fp, pathname, description)
ImportError: /home/max/Projects/as2test/env/lib/python2.7/site-packages/M2Crypto/__m2crypto.so: undefined symbol: SSLv3_method
```

**Comment by abhishek-ram** [comment]
Please take a look at [this answer] (http://stackoverflow.com/questions/10547332/install-m2crypto-on-a-virtualenv-without-system-packages) and try the solutions described there.

**Comment by maxpshaw** [comment]
Thanks, it is working now
