### ISSUE TITLE
Sending message between two PYAS2 server

### ISSUE THREAD

**Issue by iversa** [abhishek-ram/pyas2#44]
I have setup two PYAS2 servers and trying to send a message between the two I followed the instructions here in this Quick Start Guide http://pyas2.readthedocs.io/en/latest/quick-start-guide.html#

I can't get it to work. When trying to send a file this is how far it gets

I checked the logs for both the application and server. Application log only shows the Send message started with parameters: {parameters} and the server log is empty

I see that logging is set to INFO. Where can I change the log level of the application? 

Here is the screenshot
![ayas2 send message](https://user-images.githubusercontent.com/4638547/34940255-cff97d1e-f9bc-11e7-88f7-4dfa66b98b49.png)

**Comment by abhishek-ram** [comment]
It is strange that no error is logged, you can change the log level using the settings as described here http://pyas2.readthedocs.io/en/latest/configuration.html

**Comment by iversa** [comment]
I did that changing it to DEBUG and here is what I have in the pyas2.log file

```
20180115 11:15:09 INFO     : Re-send message started with parameters: "['c:\\python27\\python.exe', 'C:\\Python27\\Scripts\\django_pyas2\\manage.py', 'sendas2message', u'TelegraphRoadAS2', u'iversaas2', u'c:\\users\\admini~1\\appdata\\local\\temp\\2\\tmp7eeemk_tmp1hwedo_tmpdhbx6w_tmphelkch_850 sample with envelop info.x12']"
20180115 11:15:10 DEBUG    : Compressed message 151603291022.3720.9542029485780806733@WIN-82EFMFFL642.ec2.internal payload as:
MIME-Version: 1.0
Content-Type: application/pkcs7-mime; name="smime.p7z";
 smime-type="compressed-data"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7z"

MIAGCyqGSIb3DQEJEAEJoIAwgAIBADCABgsqhkiG9w0BCRADCAAAMIAGCSqGSIb3DQEHAaCABIIF
e3ic7Zpbb9s2FMffC/Q7EMUeNmJJedVlw4bKEuMosSVXlzTpS6HGam00tgxbXZqXfvYd6hLHEpAO
GDa/SEBsieQ5JM3zw+FfjFusy3xdniQPm/w3lG02d8vbrFwW69f5fHlyW6x3UPvyhds085a7TbFb
6gbQuiyz28UKyn9Hn5Z3+Tpb5X+8KlcbM8/z1ZcPcEcX9/m80Hfzxcdvxr2+W+R3X24XHyxJ0C5b
be5ydL8sFyhf/5XfFRu0XH8qTr9R9urli5cv3oxjPAsxE1JalmELbBkGlxyeKGaEmsRiEhOLc2zD
zTUmRBBKvmtTP3bgEaPHq/tE926bIsqe+G+KnnSR1u7hU1+6Q4Jn+M/v/2KYb+IEww+hi8El1SUj
NdYjrUYvCdOmjBr40Y9uE6kzfBXpgZgEeiKkLfRmmBvYDePEDZGnZk6UTFWQtNXUxq7bVkdq7IdB
W/X+Pa584VF6oyJ0pQIvjFCQTkcqetIGpn/QIE7PzvzrtsGNB/4FgxFEykmUh0Y3uuosHOHZTJvX
XesyP/GqJcD6MszqKwrHyDB1rZdM4aeXzaQ5acsIYf0ySg7KEk9W3poRuueh7ypdEdj4XOKJGjsT
5PmxO3H8aT25aTzGyWK5Q+F2nm8hBG+L7abYZmW+Q+UiR26xK28L9G5R3OW7DCI2LrP1PNvOUZJv
V7vWhZuts3n2K8oqqwe0yh7QxxwBFut5PkeftsUKlctVjsqi+oaW6zn8PbQOGv4+Qg+75ec12GSf
t8ASILYDT+V9nq/R191pNRuKIXiatYwdP0hOzlNYrATb+0DUEVQ15hjuJBqF6QS5YRr7gXLSqkbg
A+O3Lr7gN4hfVuswUxGOFMaJwkISIThENa8qQor16ikHU8M4tTD2A70KBqk7nPkePtOr8DNLfpk6
E5UkCp37cQJQ/UTlqW2jEb9EETUFQVOPC/Sa0ddoOqOVuZsk2n1FiMIQUE8AOUCG9ZHhFTKMDcgM
yDyDzNtUjZTbgYU3sAiIyihVmpcrv54wgNKYACJjdoGo4l1EqGUwk3NDHg8R1kOE9xGRdVahAyID
Is8gMnGunEmHENkQwmyITydNwihMIW6rpgiwaVCpTYGUc3OG5Ez0k4kBDikTxyOF90gRfVKMgZSB
lB+T4gQXYdohxWhIMbnJm2QyHTmRt88ntZWGhF4gdsU6kEgqhM2FJY644xI9SGQPEipqSMgAyQDJ
cyLlXEWjKAwv1SEpVDSkcEEIuvSDMQpTFSetPNmbaXFCJ4i6dgcVi9oWA5fkyc6L/7eo8C4qsoeK
0Uel2XmJAZUBlWdQmYZBAj95Z/NF280XREidUSLfG6uGk0cbnVAgfJnb1SdAms0tmxHzeAnF6FFi
9impd13EHigZKPnRWy91chbedDhpt16ccY7eOUmbSp4IeHqNxLvujksLeGlQZh4RELMHiNUHxKoB
MQdABkCeASSJQj9Gka/fYam4A4m1TyYEggLaKTecQBTHDS2V9QlY19uxChvbQcZFFxvYfRk2N6Ww
joeN1cPG7mEDEqXCRg7YDNg8gw2ojTgGpX4IDKMNMLbgpD5JSZzYBXWyP0p5tNRKRVwj1k8x+hhF
WPBxPFbsLiv1WeQhK3JIMQMr/yDFqChSozAIOqKetVrFMkklZ5SqkswMVj6AdPSYZPb2mhnjCtGg
q+7122JpimOeq/RP62n/tJ6ZtbofdMvAzLPq3okgbSAX1jrqanxmNtxQQmUl8r300KAB50DuiwDR
i+4hC8h9blHKJD0eNr0Te9o/sWfW8FJswObH2MxCLfeRnlLUzTatmJEmofpYEqSPE8SuEzieryC5
NNDULk4aF5ocO0J01P1fF33ywgwOqmZPzv/8Ohnq/gaVNTzWAAAAAAAAAAAAAA==
```

**Comment by abhishek-ram** [comment]
There is not much here is that all, try disabling compression and see what happens?

**Comment by iversa** [comment]
You mean compression under the partner > security settings? I did that and then nothing happens

All I have the debug log then is this

`20180115 12:02:53 INFO     : Re-send message started with parameters: "['c:\\python27\\python.exe', 'C:\\Python27\\Scripts\\django_pyas2\\manage.py', 'sendas2message', u'TelegraphRoadAS2', u'iversaas2', u'c:\\users\\admini~1\\appdata\\local\\temp\\2\\tmplx10ch_tmp7eeemk_tmp1hwedo_tmpdhbx6w_tmphelkch_850 sample with envelop info.x12']"`

It is at this step
`Signing the message using organization key as2_private.pem`

**Comment by iversa** [comment]
I think it was an issue with the first ssl keys that I created. I did them again but now I get this error

Still appears to be a ssl key issue but I'm not sure what to do

20180115 13:53:26 ERROR    : Failed to send message, error:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pyas2\management\commands\sendas2message.py", line 72, in handle
    payload = as2lib.build_message(message)
  File "c:\python27\lib\site-packages\pyas2\as2lib.py", line 375, in build_message
    str(message.organization.signature_key.certificate.path),
AttributeError: 'NoneType' object has no attribute 'certificate'

**Comment by abhishek-ram** [comment]
Looks like signature key has not been set in either the organization or the partner. Please check your setup.

**Comment by iversa** [comment]
That was the issue on my last try but when I set it I'm back at this

```
20180115 11:15:09 INFO     : Re-send message started with parameters: "['c:\\python27\\python.exe', 'C:\\Python27\\Scripts\\django_pyas2\\manage.py', 'sendas2message', u'TelegraphRoadAS2', u'iversaas2', u'c:\\users\\admini~1\\appdata\\local\\temp\\2\\tmp7eeemk_tmp1hwedo_tmpdhbx6w_tmphelkch_850 sample with envelop info.x12']"
20180115 11:15:10 DEBUG    : Compressed message 151603291022.3720.9542029485780806733@WIN-82EFMFFL642.ec2.internal payload as:
MIME-Version: 1.0
Content-Type: application/pkcs7-mime; name="smime.p7z";
 smime-type="compressed-data"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7z"

MIAGCyqGSIb3DQEJEAEJoIAwgAIBADCABgsqhkiG9w0BCRADCAAAMIAGCSqGSIb3DQEHAaCABIIF
e3ic7Zpbb9s2FMffC/Q7EMUeNmJJedVlw4bKEuMosSVXlzTpS6HGam00tgxbXZqXfvYd6hLHEpAO
GDa/SEBsieQ5JM3zw+FfjFusy3xdniQPm/w3lG02d8vbrFwW69f5fHlyW6x3UPvyhds085a7TbFb
6gbQuiyz28UKyn9Hn5Z3+Tpb5X+8KlcbM8/z1ZcPcEcX9/m80Hfzxcdvxr2+W+R3X24XHyxJ0C5b
be5ydL8sFyhf/5XfFRu0XH8qTr9R9urli5cv3oxjPAsxE1JalmELbBkGlxyeKGaEmsRiEhOLc2zD
zTUmRBBKvmtTP3bgEaPHq/tE926bIsqe+G+KnnSR1u7hU1+6Q4Jn+M/v/2KYb+IEww+hi8El1SUj
NdYjrUYvCdOmjBr40Y9uE6kzfBXpgZgEeiKkLfRmmBvYDePEDZGnZk6UTFWQtNXUxq7bVkdq7IdB
W/X+Pa584VF6oyJ0pQIvjFCQTkcqetIGpn/QIE7PzvzrtsGNB/4FgxFEykmUh0Y3uuosHOHZTJvX
XesyP/GqJcD6MszqKwrHyDB1rZdM4aeXzaQ5acsIYf0ySg7KEk9W3poRuueh7ypdEdj4XOKJGjsT
5PmxO3H8aT25aTzGyWK5Q+F2nm8hBG+L7abYZmW+Q+UiR26xK28L9G5R3OW7DCI2LrP1PNvOUZJv
V7vWhZuts3n2K8oqqwe0yh7QxxwBFut5PkeftsUKlctVjsqi+oaW6zn8PbQOGv4+Qg+75ec12GSf
t8ASILYDT+V9nq/R191pNRuKIXiatYwdP0hOzlNYrATb+0DUEVQ15hjuJBqF6QS5YRr7gXLSqkbg
A+O3Lr7gN4hfVuswUxGOFMaJwkISIThENa8qQor16ikHU8M4tTD2A70KBqk7nPkePtOr8DNLfpk6
E5UkCp37cQJQ/UTlqW2jEb9EETUFQVOPC/Sa0ddoOqOVuZsk2n1FiMIQUE8AOUCG9ZHhFTKMDcgM
yDyDzNtUjZTbgYU3sAiIyihVmpcrv54wgNKYACJjdoGo4l1EqGUwk3NDHg8R1kOE9xGRdVahAyID
Is8gMnGunEmHENkQwmyITydNwihMIW6rpgiwaVCpTYGUc3OG5Ez0k4kBDikTxyOF90gRfVKMgZSB
lB+T4gQXYdohxWhIMbnJm2QyHTmRt88ntZWGhF4gdsU6kEgqhM2FJY644xI9SGQPEipqSMgAyQDJ
cyLlXEWjKAwv1SEpVDSkcEEIuvSDMQpTFSetPNmbaXFCJ4i6dgcVi9oWA5fkyc6L/7eo8C4qsoeK
0Uel2XmJAZUBlWdQmYZBAj95Z/NF280XREidUSLfG6uGk0cbnVAgfJnb1SdAms0tmxHzeAnF6FFi
9impd13EHigZKPnRWy91chbedDhpt16ccY7eOUmbSp4IeHqNxLvujksLeGlQZh4RELMHiNUHxKoB
MQdABkCeASSJQj9Gka/fYam4A4m1TyYEggLaKTecQBTHDS2V9QlY19uxChvbQcZFFxvYfRk2N6Ww
joeN1cPG7mEDEqXCRg7YDNg8gw2ojTgGpX4IDKMNMLbgpD5JSZzYBXWyP0p5tNRKRVwj1k8x+hhF
WPBxPFbsLiv1WeQhK3JIMQMr/yDFqChSozAIOqKetVrFMkklZ5SqkswMVj6AdPSYZPb2mhnjCtGg
q+7122JpimOeq/RP62n/tJ6ZtbofdMvAzLPq3okgbSAX1jrqanxmNtxQQmUl8r300KAB50DuiwDR
i+4hC8h9blHKJD0eNr0Te9o/sWfW8FJswObH2MxCLfeRnlLUzTatmJEmofpYEqSPE8SuEzieryC5
NNDULk4aF5ocO0J01P1fF33ywgwOqmZPzv/8Ohnq/gaVNTzWAAAAAAAAAAAAAA==
```

**Comment by abhishek-ram** [comment]
I need to take a look at this message me on skype at abhishek.ram2

**Comment by iversa** [comment]
I have sent you a Skype invite

**Comment by dtstbnow** [comment]
Has there been any progress on this?  I am experiencing the same issues, it appears to be happening during the signer.sign call in sign_payload.

**Comment by abhishek-ram** [comment]
pyAS2 is currently not supported on windows as there are issues installing the dependant library M2Crypto

**Comment by dtstbnow** [comment]
I encountered this on Debian per M2Crypto's recommended installation instructions.
