### ISSUE TITLE
Running pyas2 on Heroku

### ISSUE THREAD

**Issue by vpontis** [abhishek-ram/pyas2#46]
Has anyone ran this server on Heroku? 

I am getting the following error which is similar to https://github.com/abhishek-ram/pyas2/issues/30 but I think the solution will have to be different because the way Heroku installs packages.

```
2018-03-05T22:20:16.974472+00:00 heroku[web.1]: - Starting process with command `python manage.py runas2server`
2018-03-05T22:20:20.281704+00:00 heroku[web.1]: - State changed from starting to crashed
2018-03-05T22:20:20.195261+00:00 app[web.1]: - Traceback (most recent call last):
2018-03-05T22:20:20.195296+00:00 app[web.1]: -     execute_from_command_line(sys.argv)
2018-03-05T22:20:20.195287+00:00 app[web.1]: -   File "manage.py", line 22, in <module>
2018-03-05T22:20:20.195310+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
2018-03-05T22:20:20.195348+00:00 app[web.1]: -     utility.execute()
2018-03-05T22:20:20.195425+00:00 app[web.1]: -     django.setup()
2018-03-05T22:20:20.195360+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
2018-03-05T22:20:20.195436+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
2018-03-05T22:20:20.195443+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
2018-03-05T22:20:20.195494+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
2018-03-05T22:20:20.195523+00:00 app[web.1]: -     self.models_module = import_module(models_module_name)
2018-03-05T22:20:20.195441+00:00 app[web.1]: -     apps.populate(settings.INSTALLED_APPS)
2018-03-05T22:20:20.195529+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2018-03-05T22:20:20.195491+00:00 app[web.1]: -     app_config.import_models(all_models)
2018-03-05T22:20:20.195537+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/pyas2/models.py", line 6, in <module>
2018-03-05T22:20:20.195603+00:00 app[web.1]: -     from pyas2 import pyas2init
2018-03-05T22:20:20.195606+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/pyas2/pyas2init.py", line 5, in <module>
2018-03-05T22:20:20.195533+00:00 app[web.1]: -     __import__(name)
2018-03-05T22:20:20.195611+00:00 app[web.1]: -     from pyas2 import as2utils
2018-03-05T22:20:20.195615+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/pyas2/as2utils.py", line 12, in <module>
2018-03-05T22:20:20.195637+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/M2Crypto/__init__.py", line 26, in <module>
2018-03-05T22:20:20.195635+00:00 app[web.1]: -     from M2Crypto import BIO, SMIME, X509
2018-03-05T22:20:20.195690+00:00 app[web.1]: -     from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
2018-03-05T22:20:20.195693+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 15, in <module>
2018-03-05T22:20:20.195695+00:00 app[web.1]: -     from M2Crypto import BIO, m2, util
2018-03-05T22:20:20.195696+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/M2Crypto/BIO.py", line 9, in <module>
2018-03-05T22:20:20.195701+00:00 app[web.1]: -     from M2Crypto import m2, six, util
2018-03-05T22:20:20.195703+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/M2Crypto/m2.py", line 30, in <module>
2018-03-05T22:20:20.195706+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/M2Crypto/m2crypto.py", line 26, in <module>
2018-03-05T22:20:20.195704+00:00 app[web.1]: -     from M2Crypto.m2crypto import *
2018-03-05T22:20:20.195710+00:00 app[web.1]: -     _m2crypto = swig_import_helper()
2018-03-05T22:20:20.195713+00:00 app[web.1]: -   File "/app/.heroku/python/lib/python2.7/site-packages/M2Crypto/m2crypto.py", line 22, in swig_import_helper
2018-03-05T22:20:20.195738+00:00 app[web.1]: -     _mod = imp.load_module('_m2crypto', fp, pathname, description)
2018-03-05T22:20:20.195746+00:00 app[web.1]: - ImportError: /app/.heroku/python/lib/python2.7/site-packages/M2Crypto/_m2crypto.so: undefined symbol: sslv3_method```

**Comment by vpontis** [comment]
For everyone out there following my trials and tribulations today, PyAS2 will not work on Heroku because Heroku does not have persistent file storage and PyAS2 uses local files to store inbox, outbox, certificates etc. 

But I got M2Crypto working using this buildpack on cedar-14 https://github.com/huxley/heroku-buildpack-SWIG-python

I am now going to try DigitalOcean! Let me know if anyone prefers a different hosting service to run these servers...
